In [1]:
import torch
print(torch.version.cuda)
print(torch.cuda.is_available())

None
False

In [2]:
import torch
print(torch.__version__)
print(torch.version.cuda)
print(torch.backends.cudnn.version())
print(torch.cuda.is_available())

2.9.0+cpu
None
None
False

In [3]:
from datasets import ImageDataset, SegmentDataset
from preprocessors import LabeledSegmentsCreator,SuperpixelSegmentsCreator
from models import HistogramBaseModel
import config
import numpy as np
import mlflow
# Initialize the image dataset with the specified paths
image_dataset=ImageDataset(dataset_name="process_bainite_dataset",
                 image_data_path=config.RAW_BAINITE_IMAGE_DATASET_PATH,
                 image_label_data_path=config.RAW_BAINITE_LABEL_DATASET_PATH,
    )
raw_images_df=image_dataset.load_meta_data()
raw_images_df

,image_path,json_path,martensite_count,bainite_count
0,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,8.0,4.0
1,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,6.0,5.0
2,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,9.0,8.0
3,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,None,NaN,NaN
4,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,None,NaN,NaN
5,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,None,NaN,NaN

In [4]:
raw_images_df = raw_images_df[raw_images_df['json_path'].notnull()]
raw_images_df

,image_path,json_path,martensite_count,bainite_count
0,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,8.0,4.0
1,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,6.0,5.0
2,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,9.0,8.0

In [5]:
# Initialize the segment dataset
segment_dataset = SegmentDataset(dataset_name="process_bainite_segments",
                                  image_data_path=config.RAW_BAINITE_SEGMENTS_DATASET_PATH,
                                  image_label_data_path=config.RAW_BAINITE_SEGMENTS_LABELS_DATASET_PATH)
# Create the labeled segments
labeled_segments_creator = LabeledSegmentsCreator(input_dataset=image_dataset, output_dataset=segment_dataset)
labeled_segments_creator.create_segments()

Created dir: C:\Users\hallo\Desktop\Bainitu_segmenation\data_labeling\src\results\process_bainite_segments
Warning: No JSON path for C:\Users\hallo\Desktop\Bainitu_segmenation\data_labeling\src\raw_images\798-DQ-hollow_1000x-1.tif, skipping...
Warning: No JSON path for C:\Users\hallo\Desktop\Bainitu_segmenation\data_labeling\src\raw_images\798-DQ-hollow_1000x-2.tif, skipping...
Warning: No JSON path for C:\Users\hallo\Desktop\Bainitu_segmenation\data_labeling\src\raw_images\798-DQ-hollow_1000x-3.tif, skipping...
Created 5 segments from 6 images.

In [6]:
segment_dataset.load_meta_data()

,image_path,json_path,label
0,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,upper_bainite
1,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
2,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
3,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
4,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
5,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
6,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
7,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
8,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
9,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
10,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
11,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
12,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
13,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
14,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
15,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
16,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
17,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
18,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
19,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
20,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
21,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
22,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
23,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
24,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
25,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
26,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
27,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
28,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
29,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
30,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
31,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,bainite
32,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
33,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
34,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
35,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
36,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
37,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
38,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
39,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite
40,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,C:\Users\hallo\Desktop\Bainitu_segmenation\dat...,martensite

In [ ]:
from preprocessors import FelzenszwalbSegmentsCreator

felzenszwalb_parameters = {
        # "scale_ratio" : {'type' : 'float', 'min' : 0.00001, 'max' : 0.00005},
        "scale" : {'type' : 'int', 'min' : 5, 'max' : 230},
        "min_size" : {'type' : 'int', 'min' : 10, 'max' : 600},
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}


segment_creator = FelzenszwalbSegmentsCreator(input_dataset=self.src_segment_dataset)
segment_creator.create_segments(segmentation_parameters, segmentation_out_dataset) 
post_segmentation_stats = self.segment_creator.get_post_segmentation_statistics() 
segmentation_output_dataset = segmentation_out_dataset
model = HistogramBaseModel(input_dataset=self.segmentation_output_dataset, **model_hyperparameters)

In [7]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser

c:\Users\hallo\Desktop\Bainitu_segmenation\venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
model_parameters = {
    'n_estimators': {'type': 'int', 'min': 50, 'max': 200},
    'max_depth': {'type': 'int', 'min': 5, 'max': 20},
    'min_samples_split': {'type': 'int', 'min': 2, 'max': 10},
    'min_samples_leaf': {'type': 'int', 'min': 1, 'max': 5},
    'max_features': {'type': 'int', 'min': 1, 'max': 5},   
    'bins': {'type': 'int', 'min': 64, 'max': 256}
}

In [ ]:
model_parameters = {
    'n_estimators': {'type': 'int', 'min': 50, 'max': 200},
    'max_depth': {'type': 'int', 'min': 5, 'max': 20},
    'min_samples_split': {'type': 'int', 'min': 2, 'max': 10},
    'min_samples_leaf': {'type': 'int', 'min': 1, 'max': 5},
    'max_features': {'type': 'int', 'min': 1, 'max': 5},   
    'bins': {'type': 'int', 'min': 64, 'max': 256}
}

slic_parameters = {
        "pixels_per_superpixel" : {'type' : 'int', 'min' : 8000, 'max' : 30000},
        "compactness" : {'type' : 'float', 'min' : 0.4, 'max' : 1}, # consider 0.5
        # "min_cluster_size" : {'type' : 'int', 'min' : 30, 'max' : 100},
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}

felzenszwalb_parameters = {
        # "scale_ratio" : {'type' : 'float', 'min' : 0.00001, 'max' : 0.00005},
        "scale" : {'type' : 'int', 'min' : 5, 'max' : 230},
        "min_size" : {'type' : 'int', 'min' : 10, 'max' : 600},
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}

# felzenszwalb_parameters = {
#         # "scale_ratio" : {'type' : 'float', 'min' : 0.00001, 'max' : 0.00005},
#         "scale" : {'type' : 'int', 'min' : 160, 'max' : 350},
#         "min_size" : {'type' : 'int', 'min' : 250, 'max' : 500},
#         "sigma" : {'type' : 'float', 'min' : 0.3, 'max' : 0.6}
# }

optuna_optimiser_felzenszwalb = OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="felzenszwalb", n_trials=5,
                                   model_hyperparameters=model_parameters, segmentation_parameters = felzenszwalb_parameters, maximize=True, metric_name='f1', experiment_name="Upper_Felzenszwalb")

2026/01/27 17:30:39 INFO mlflow.tracking.fluent: Experiment with name 'ProcessX_Felzenszwalb_min_nonadj68f667fc-b6f4-4da6-8039-e56c8c5e3718' does not exist. Creating a new experiment.

In [ ]:
optuna_optimiser_felzenszwalb.optimise()

[I 2026-01-27 17:30:40,401] A new study created in memory with name: no-name-3f872984-d796-43f8-b0ba-ab64aafd83eb

Created dir: C:\Users\hallo\Desktop\Bainitu_segmenation\data_labeling\src\results\felzenszwalb_170b7dff41eb
Debug: segment creation done
Processing 0 fold...
Processing 1 fold...
Processing 2 fold...
Processing 3 fold...
Processing 4 fold...

2026/01/27 17:33:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[I 2026-01-27 17:33:33,671] Trial 0 finished with value: 0.7160062639800066 and parameters: {'n_estimators': 88, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 3, 'bins': 147, 'scale': 28, 'min_size': 523, 'sigma': 0.49419673915128537}. Best is trial 0 with value: 0.7160062639800066.

🏃 View run OptunaOptimiser {'n_estimators': 88, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': 3, 'bins': 147, 'scale': 28, 'min_size': 523, 'sigma': 0.49419673915128537} at: http://127.0.0.1:5000/#/experiments/937601968208054356/runs/4d8c32f85bb3430dbe272875ae857e87
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/937601968208054356
Created dir: C:\Users\hallo\Desktop\Bainitu_segmenation\data_labeling\src\results\felzenszwalb_859c3e76b340

In [ ]:
felzenszwalb_parameters = {
        # "scale_ratio" : {'type' : 'float', 'min' : 0.00001, 'max' : 0.00005},
        "scale" : {'type' : 'int', 'min' : 230, 'max' : 1000},
        "min_size" : {'type' : 'int', 'min' : 400, 'max' : 1800},
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}


optuna_optimiser_felzenszwalb = OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="felzenszwalb", n_trials=30,
                                   model_hyperparameters=model_parameters, segmentation_parameters = felzenszwalb_parameters, maximize=True, metric_name='f1', experiment_name="Felzenszwalb_2")
optuna_optimiser_felzenszwalb.optimise()

In [ ]:
felzenszwalb_parameters = {
        # "scale_ratio" : {'type' : 'float', 'min' : 0.00001, 'max' : 0.00005},
        "scale" : {'type' : 'int', 'min' : 1, 'max' : 5},
        "min_size" : {'type' : 'int', 'min' : 400, 'max' : 1800},
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}


optuna_optimiser_felzenszwalb = OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="felzenszwalb", n_trials=30,
                                   model_hyperparameters=model_parameters, segmentation_parameters = felzenszwalb_parameters, maximize=True, metric_name='f1', experiment_name="Felzenszwalb_3")
optuna_optimiser_felzenszwalb.optimise()

In [ ]:
optuna_optimiser_slic = OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="slic", n_trials=100,
                                   model_hyperparameters=model_parameters, segmentation_parameters = slic_parameters, maximize=True, metric_name='f1', experiment_name="Slic_min_nonadj")
optuna_optimiser_slic.optimise()

In [ ]:
watershed_parameters = {
        "connectivity" : {'type' : 'int', 'min' : 0, 'max' : 4},
}

optuna_optimiser_watershed = OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="watershed", n_trials=10,
                                   model_hyperparameters=model_parameters, segmentation_parameters = watershed_parameters, maximize=True, metric_name='f1', experiment_name="watershed_min_nonadj")
optuna_optimiser_watershed.optimise()

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser


model_parameters = {
    'n_estimators': {'type': 'int', 'min': 50, 'max': 200},
    'max_depth': {'type': 'int', 'min': 5, 'max': 20},
    'min_samples_split': {'type': 'int', 'min': 2, 'max': 10},
    'min_samples_leaf': {'type': 'int', 'min': 1, 'max': 5},
    'max_features': {'type': 'int', 'min': 1, 'max': 5},   
    'bins': {'type': 'int', 'min': 64, 'max': 256}
}

slic_parameters = {
        "pixels_per_superpixel" : {'type' : 'int', 'min' : 10000, 'max' : 30000},
        "compactness" : {'type' : 'float', 'min' : 0.4, 'max' : 0.9}, # consider 0.5
        "sigma" : {'type' : 'float', 'min' : 0.6, 'max' : 1.5}
}


optuna_optimiser_slic = OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="slic", n_trials=100,
                                   model_hyperparameters=model_parameters, segmentation_parameters = slic_parameters, maximize=True, metric_name='f1', experiment_name="Slic_bin_limit_new_data")

In [ ]:
mlflow.end_run()

In [ ]:
optuna_optimiser_slic.optimise()

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser


model_parameters = {
    'n_estimators': {'type': 'int', 'min': 50, 'max': 200},
    'max_depth': {'type': 'int', 'min': 5, 'max': 20},
    'min_samples_split': {'type': 'int', 'min': 2, 'max': 10},
    'min_samples_leaf': {'type': 'int', 'min': 1, 'max': 5},
    'max_features': {'type': 'int', 'min': 1, 'max': 5},   
    'bins': {'type': 'int', 'min': 64, 'max': 256}
}

watershed_parameters = {
        "connectivity" : {'type' : 'int', 'min' : 0, 'max' : 4},
}


optuna_optimiser_watershed= OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="watershed", n_trials=30,
                                   model_hyperparameters=model_parameters, segmentation_parameters = watershed_parameters, maximize=True, metric_name='f1', experiment_name="Watershed_bin_limit_new_data")

In [ ]:
optuna_optimiser_watershed.optimise()

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser


model_parameters = {
    'lr': {'type': 'float', 'min': 1e-4, 'max': 1e-1},
    'epochs': {'type': 'int', 'min': 2, 'max': 10},
}

slic_parameters = {
        "pixels_per_superpixel" : {'type' : 'int', 'min' : 8000, 'max' : 30000},
        "compactness" : {'type' : 'float', 'min' : 0.4, 'max' : 1}, # consider 0.5
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}

optuna_optimiser= OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="ResNet50", segmentation="slic", n_trials=10,
                                   model_hyperparameters=model_parameters, segmentation_parameters = slic_parameters, maximize=True, metric_name='f1', experiment_name="ResNet50")

In [ ]:
optuna_optimiser.optimise()

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser


model_parameters = {
    'lr': {'type': 'float', 'min': 1e-4, 'max': 1e-1},
    'epochs': {'type': 'int', 'min': 3, 'max': 100},
}

slic_parameters = {
        "pixels_per_superpixel" : {'type' : 'int', 'min' : 8000, 'max' : 25000},
        "compactness" : {'type' : 'float', 'min' : 0.6, 'max' : 0.8}, # consider 0.5
        "sigma" : {'type' : 'float', 'min' : 0.1, 'max' : 1.5}
}

optuna_optimiser= OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="efficientnet_b0", segmentation="slic", n_trials=100,
                                   model_hyperparameters=model_parameters, segmentation_parameters = slic_parameters, maximize=True, metric_name='f1', experiment_name="efficientnet_b0")
optuna_optimiser.optimise()

In [ ]:
!pip install torchvision

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import io
from PIL import Image
def plot_confusion_matrix(cm, labels):

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
    plt.ylabel('True label')
    plt.xlabel('Predicted label')

    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    plt.close()
    buf.seek(0)

    # Convert buffer to a PIL Image for MLflow
    img = Image.open(buf)
    return img


img=plot_confusion_matrix(cm, labels)
img.show()

In [ ]:
segment_dataset = SegmentDataset(dataset_name="slic_00e6a9d78e98",
                                  image_data_path=config.SUPERPIXEL_BAINITE_SEGMENTS_DATASET_PATH,
                                  image_label_data_path=config.SUPERPIXEL_BAINITE_SEGMENTS_DATASET_PATH)
# Create the labeled segments
labeled_segments_creator = LabeledSegmentsCreator(input_dataset=image_dataset, output_dataset=segment_dataset)
labeled_segments_creator.create_segments()

In [ ]:
import numpy as np

data = np.random.randn(10)
print(data)

hist, bin_edges = np.histogram(data, bins=10)
print(hist)
print(bin_edges)

In [ ]:
import matplotlib.pyplot as plt

plt.hist(data, bins=10, edgecolor='black')
plt.show()

In [ ]:
import cv2
from skimage.segmentation import felzenszwalb
from skimage.segmentation import mark_boundaries
from skimage.util import img_as_float
import matplotlib.pyplot as plt

image = cv2.imread(r"C:\Users\hallo\Desktop\Bainitu_segmenation\data_labeling\src\raw_images\797-DQ-full_1000x-1.tif")
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)[:300]
# Convert to float for segmentation (values between 0 and 1) TODO ???
img_float = img_as_float(gray)
segments = felzenszwalb(
    img_float,
    scale=800,
    #sigma=1,
)
fig, ax = plt.subplots(2, 2, figsize=(10, 10), sharex=True, sharey=True)

ax[0, 0].imshow(mark_boundaries(img_float, segments))
ax[0, 0].set_title("Felzenszwalbs's method")

for a in ax.ravel():
    a.set_axis_off()

plt.tight_layout()
plt.show()

In [ ]:
from datasets import ImageDataset, SegmentDataset
from preprocessors import LabeledSegmentsCreator,SuperpixelSegmentsCreator
from models import HistogramBaseModel
import config
import numpy as np
import mlflow
# Initialize the image dataset with the specified paths
image_dataset=ImageDataset(dataset_name="test_felzenszwalb_segments",
                 image_data_path=config.TEST_DATASET_PATH,
                 image_label_data_path=config.TEST_LABEL_DATASET_PATH,
    )
raw_images_df=image_dataset.load_meta_data()
raw_images_df

In [ ]:
raw_images_df = raw_images_df[raw_images_df['json_path'].notnull()]
raw_images_df

In [ ]:
# Initialize the segment dataset
test_dataset = SegmentDataset(dataset_name="test_felzenszwalb_segments",
                                  image_data_path=config.RAW_BAINITE_SEGMENTS_DATASET_PATH,
                                  image_label_data_path=config.RAW_BAINITE_SEGMENTS_LABELS_DATASET_PATH)
# Create the labeled segments
labeled_segments_creator = LabeledSegmentsCreator(input_dataset=image_dataset, output_dataset=test_dataset)
labeled_segments_creator.create_segments()

In [ ]:
test_dataset.load_meta_data()

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser

model_parameters = {
    'n_estimators': 200,
    'max_depth': 20,
    'min_samples_split': 10,
    'min_samples_leaf':  5,
    'max_features':  5,
    'bins': 241
}


felzenszwalb_parameters = {
        "scale" : 167,
        "min_size" : 493,
        "sigma" : 0.33
}
slic_parameters = {
        "pixels_per_superpixel" : 11843,
        "compactness" : 0.79,
        "sigma" : 0.62
}



optuna_optimiser_felzenszwalb = OptunaOptimiser(src_segment_dataset=test_dataset, model_name="HistogramBaseModel", segmentation="slic", n_trials=30,
                                   model_hyperparameters=model_parameters, segmentation_parameters = slic_parameters, maximize=True, metric_name='f1', experiment_name="Test_slic")
optuna_optimiser_felzenszwalb.predict_on_test_dataset(test_dataset, "mlflow-artifacts:/707964529830257107/models/m-87ce1d5125554f40ab7aa3120b59d828/artifacts", slic_parameters)

In [ ]:
# GRID

In [ ]:
from datasets import ImageDataset, SegmentDataset
from preprocessors import LabeledSegmentsCreator,GridSegmentsCreator
from models import HistogramBaseModel
import config
import numpy as np
import mlflow
# Initialize the image dataset with the specified paths
image_dataset=ImageDataset(dataset_name="raw_bainite_dataset",
                 image_data_path=config.RAW_BAINITE_IMAGE_DATASET_PATH,
                 image_label_data_path=config.RAW_BAINITE_LABEL_DATASET_PATH,
    )
raw_images_df=image_dataset.load_meta_data()
raw_images_df

In [ ]:
raw_images_df = raw_images_df[raw_images_df['json_path'].notnull()]
raw_images_df

In [ ]:
# Initialize the segment dataset
segment_dataset = SegmentDataset(dataset_name="grid_bainite_segments",
                                  image_data_path=config.RAW_BAINITE_SEGMENTS_DATASET_PATH,
                                  image_label_data_path=config.RAW_BAINITE_SEGMENTS_LABELS_DATASET_PATH)
# Create the labeled segments
# labeled_segments_creator = GridSegmentsCreator(input_dataset=image_dataset, output_dataset=segment_dataset)
# labeled_segments_creator.create_segments()

In [ ]:
# segment_dataset.load_meta_data()

In [ ]:
from optimisers.optuna_optimiser.optuna_optimiser import OptunaOptimiser

grid_parameters = {
        "grid_cols" : {'type' : 'int', 'min' : 10, 'max' : 30},
        "grid_rows" : {'type' : 'int', 'min' : 10, 'max' : 30}
}

# model_parameters = {
#     'lr': {'type': 'float', 'min': 1e-4, 'max': 1e-1},
#     'epochs': {'type': 'int', 'min': 3, 'max': 100},
# }


optuna_optimiser_felzenszwalb = OptunaOptimiser(src_segment_dataset=segment_dataset, model_name="HistogramBaseModel", segmentation="grid", n_trials=3,
                                   model_hyperparameters=model_parameters, segmentation_parameters = grid_parameters, maximize=True, metric_name='f1', experiment_name="Grid")
optuna_optimiser_felzenszwalb.optimise()